#include "first_legal.h"

#include <stddef.h>

#include "../movegen.h"

static bool firstLegalChooseMove(Board* b, const SearchLimits* limits, SearchResult* result)
{
    (void)limits;

    result->bestMove = NO_MOVE;
    result->nodes = 0;
    result->hasScore = false;
    result->score = 0;

    Move moves[MAX_MOVES];
    int  n = generateAllMoves(b, moves);
    for (int i = 0; i < n; i++)
    {
        result->nodes++;
        if (moveIsLegal(b, moves[i]))
        {
            result->bestMove = moves[i];
            return true;
        }
    }

    return true;
}

const Algorithm FirstLegalAlgorithm = {
    "first_legal", "returns the first legal move generated by the core move generator",
    NULL,          NULL,
    NULL,          firstLegalChooseMove,
};
