#include "first_legal.h"

#include <stddef.h>

#include "../algohelpers.h"

static bool firstLegalChooseMove(Board* b, const SearchLimits* limits, SearchResult* result)
{
    (void)limits;
    searchResultInit(result);

    Move moves[MAX_MOVES];
    int  n = legalMoves(b, moves);
    if (n > 0)
    {
        result->bestMove = moves[0];
        result->nodes = 1;
    }
    return true;
}

const Algorithm FirstLegalAlgorithm = {
    "first_legal", "returns the first legal move generated by the core move generator",
    NULL,          NULL,
    NULL,          firstLegalChooseMove,
};
